---
- name: Create monitoring namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: Ensure Helm is installed
  get_url:
    url: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
  register: helm_download

- name: Extract helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    copy: no

- name: Add Prometheus community helm repo
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  args:
    creates: /tmp/prometheus_repo_added

- name: Update helm repos
  command: helm repo update

- name: Install Prometheus
  command: helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace
  args:
    creates: /tmp/prometheus_installed

- name: Install Grafana
  command: helm install grafana prometheus-community/grafana --namespace monitoring --create-namespace
  args:
    creates: /tmp/grafana_installed
