apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword }}
  POSTGRES_DB: {{ .Values.postgresDatabase }}
