apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yassineamri722/flask-react-devops-app.git'
    targetRevision: dev
    path: charts/backend
    helm:
      valueFiles:
        - values.yml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
