backend:
  image:
    repository: yassineamri/flask-backend   
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000

frontend:
  image:
    repository: yassineamri/react-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 30080
