backend:
  image:
    repository: yassineamri/flask-backend   
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000

frontend:
  image:
    repository: yassineamri/react-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 3000
    nodePort: 30080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.local
      paths:
        - path: /front
          pathType: Prefix
          service:
            name: frontend
            port: 3000
    - host: backend.local
      paths:
        - path: /back
          pathType: Prefix
          service:
            name: backend
            port: 5000
  tls: []
