backend:
  image:
    repository: yassineamri/backend
    tag: 8d3aa46e91b8b958491b65b4d8cd8dd2489da740
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
frontend:
  image:
    repository: yassineamri/frontend
    tag: 8d3aa46e91b8b958491b65b4d8cd8dd2489da740
    pullPolicy: Always
  service:
    type: NodePort
    port: 3000
    nodePort: 30080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 3000
    - host: backend.local
      paths:
        - path: /
          pathType: Prefix
          service:
            name: backend
            port: 5000
  tls: []
